#!/bin/bash -e
exec > >(tee -a -i /var/log/runonce.log) 2>&1

# Create or modify group bluetooth.
if ! getent group 'bluetooth'; then
  groupadd -r -g 112 bluetooth || true
else
  groupmod -g 112 bluetooth || true
fi
# Create or modify group lpadmin.
if ! getent group 'lpadmin'; then
  groupadd -r -g 113 lpadmin || true
else
  groupmod -g 113 lpadmin || true
fi
# Create or modify group scanner.
if ! getent group 'scanner'; then
  groupadd -r -g 122 scanner || true
else
  groupmod -g 122 scanner || true
fi
# Create or modify group kali.
if ! getent group 'kali'; then
  groupadd -g 1000 kali || true
else
  groupmod -g 1000 kali || true
fi


# Default groups.
kali_groups="adm,audio,cdrom,dialout,dip,games,input,netdev,plugdev,render,\
staff,sudo,systemd-journal,users,video,scanner,kali"

# Check that the application groups exist.
app_groups="wireshark kismet i2c"
for g in $app_groups; do
  if getent group "$g" >/dev/null; then
    kali_groups+=",$g"
  fi
done

# Add the kali user and give them all the access they need.
if ! getent passwd 'kali'; then
  if [ $(arch) == 'armv6l' ]; then
    adduser --gecos "" --uid 1000 --gid 1000 --shell /usr/bin/bash --disabled-password kali
  else
    adduser --gecos "" --uid 1000 --gid 1000 --shell /usr/bin/zsh --disabled-password kali
  fi
  usermod -a -G "$kali_groups" kali
  echo 'kali:kali' | chpasswd
fi

# Reload and trigger udev rule
udevadm control --reload-rules
udevadm trigger
