DESCRIPTION = "A WeakMethod class for storing bound methods using weak references."
HOMEPAGE = "https://github.com/twang817/weakrefmethod"
SECTION = "devel/python"
LICENSE = "PSF"
LIC_FILES_CHKSUM = "file://LICENSE;md5=dd98d01d471fac8d8dbdd975229dba03"

SRC_URI[md5sum] = "39e7450191dea0b17a646b929784ac6f"
SRC_URI[sha256sum] = "37bc1fbb5575acf82172d4eb7b6fc4412d77d5a1d70dff2c1f8a4574301cda66"

inherit pypi
