DESCRIPTION = "A very small text templating language"
HOMEPAGE = "http://pythonpaste.org/tempita/"
SECTION = "devel/python"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://setup.py;beginline=33;endline=33;md5=2d33c00f47720c7e35e1fdb4b9fab027"

PYPI_PACKAGE = "Tempita"

SRC_URI[md5sum] = "365c3b4f36435e2178902d5619301140"
SRC_URI[sha256sum] = "38392bb708a10128419f75fa9120a6d2c8d137013b353968e5008a77a5c7a2ca"

inherit pypi
