DESCRIPTION = "Python Dogpile Cache: A caching front-end based on the Dogpile lock"
HOMEPAGE = "https://pypi.python.org/pypi/dogpile.cache"
SECTION = "devel/python"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://LICENSE;md5=e8d5890806254a2648269bb4029f74c6"

SRC_URI[md5sum] = "d48b4752b404e2e2a33f984d261fff7d"
SRC_URI[sha256sum] = "b348835825c9dcd251d9aad1f89f257277ac198a3e35a61980ab4cb28c75216b"

inherit pypi


